# Experiment with arm64

name: arm64

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04-arm

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Status
        run: |
          uname -a
          cat /proc/cpuinfo
          docker version
          docker info

      - name: Container
        run: |
          docker pull r-base
          docker run --rm r-base R -q -e 'R.version'

          
