# Experiment with arm64

name: arm64

on:
  push:
  pull_request:
  #release:
  workflow_dispatch:

jobs:
  setup:
    needs: create_gha_builder
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/gha_noodling'
    container:
      image: eddelbuettel/gha_r2u_build:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Crete Config and Cache
        run: |
          r -e 'r2u:::.createDefaultConfiguration()'
          r -e 'r2u:::.loadDB()'
          r -e 'r2u:::.loadAP()'
      - name: Upload Config
        uses: actions/upload-artifact@v4.4.0
        with:
          name: r2u_config
          path: ~/.local/share/R/r2u
          
  make_matrix:
    needs: setup
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/gha_noodling'
    outputs:
      runmatrix: ${{ steps.makematrixstep.outputs.matrixoutput }}
    steps:  
      ## see https://www.kenmuse.com/blog/dynamic-build-matrices-in-github-actions/
      - id: makematrixstep
        run: |
          TARGETS=$(echo '["magrittr", "Rcpp", "utf8", "fansi", "curl", "xfun"]')
          echo "matrixoutput=$(jq -cn --argjson environments "$TARGETS" '{target: $environments}')" >> $GITHUB_OUTPUT        
          
  build_package:
    needs: make_matrix
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/gha_noodling'
    container:
      image: eddelbuettel/gha_r2u_build:noble
    strategy:
      matrix: ${{ fromJson(needs.make_matrix.outputs.runmatrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Config
        uses: actions/download-artifact@v4.1.8
        with:
          name: r2u_config
          path: ~/.local/share/R/r2u
      - name: Build
        run:  r2u.r -v -d -c -f -r noble package ${{ matrix.target }}
      - name: Upload Deb
        uses: actions/upload-artifact@v4.4.0
        with:
          name: deb-${{ matrix.target }}
          path: /var/local/r2u/ubuntu/pool/dists/noble/main/

  make_second_matrix:
    needs: build_package
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/gha_noodling'
    outputs:
      runmatrix: ${{ steps.makematrixstep.outputs.matrixoutput }}
    steps:  
      ## see https://www.kenmuse.com/blog/dynamic-build-matrices-in-github-actions/
      - id: makematrixstep
        run: |
          TARGETS=$(echo '["magrittr", "Rcpp", "utf8", "fansi", "curl", "xfun"]')
          echo "matrixoutput=$(jq -cn --argjson environments "$TARGETS" '{target: $environments}')" >> $GITHUB_OUTPUT        
          
  release_packages:
    needs: make_second_matrix
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/gha_noodling'
    container:
      image: eddelbuettel/gha_r2u_build:noble
    strategy:
      matrix: ${{ fromJson(needs.make_second_matrix.outputs.runmatrix) }}
    steps:
      - name: Get Deb
        uses: actions/download-artifact@v4.1.8
        with:
          name: deb-${{ matrix.target }}
          path: /var/local/r2u/ubuntu/pool/dists/noble/main/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: /var/local/r2u/ubuntu/pool/dists/noble/main/*deb
          make_latest: true
          prerelease: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
         
  create_gha_builder:
    needs: create_builder
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/gha_noodling'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: gha-r2u-builder
          tags: eddelbuettel/gha_r2u_build:noble
          
  create_builder:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/gha_noodling'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: r2u-builder
          tags: eddelbuettel/r2u_build:noble

